digitalbazaar/forge

js/cipherModes.js
There's a bug in transformIV when the iv is given as a byte array. The resulting byte buffer is always empty. This fix transforms the iv byte array into the byte buffer correctly.
This fix is critical for production use! Please do your best to merge as soon as possible.
=> fix AES decipher iv transformation from byte array to byte buffer

js/jsbn.js
This bug was found by [Cure53](https://cure53.de) during a security review of [Whiteout Mail](https://whiteout.io). The following comments are copied from the audit report:
In the file forge/js/jsbn.js the method bnGetPrng() is present, tasked with generating a pseudo-random big number. This method is used during RSA key generation in the Miller Rabin pseudo-prime test. The following line gets a random number and converts it as uniformly distributed into a byte ([0..255]):
x[i] = Math.floor(Math.random() * 0xFF);
Unfortunately the value of 255 will never be reached because Math.random() generates a value between 0 inclusive and 1 exclusive. This results in a subtle weakness in the Miller-Rabin pseudoprime test. It should be corrected to the following code:
x[i] = Math.floor(Math.random() …
=> [WO-03-005] Fix off-by-one Error in Prime Worker Code of Forge library (Low)

js/x509.js
While I was playing with signing certificates, it occurred that I may have made a poor API choice.
The API (using non-default values) would looks like:
```
{
name: 'authorityKeyIdentifier',
keyIdentifier: this._ca.cert.generateSubjectKeyIdentifier().getBytes(),
authorityCertIssuer: this._ca.cert.issuer,
serialNumber: this._ca.cert.serialNumber
}
```
Currently it requires `authorityCertIssuer: this._ca.cert.issuer.attributes`.
It's a minor but breaking change, so I guess it's best to fix it asap.
=> More intuitive API for authorityKeyIdentifier extension

js/tls.js
Made sure the pull request is now based on the latest 0.6.x release of Forge.
According to the TLS specification the handshake message certificate_request, sent as part of the server_hello messages, should include the length of each individual distinguished name before the distinguished name itself.
=> Distinguished name length in certificate request

js/rsa.js
The same comment is expressed 7 lines earlier.
=> Remove redundant comment

js/tls.js
TLS messages of type handshake, alert or change_cipher_spec are not allowed to be empty.
=> Invalid empty tls messages

js/oids.js
Just a couple of missing oids for better identification when parsing exts.
=> Add couple of missing oids

js/forge.js
This patch fixes module loading on Node.js.
=> Fix Node module loading

lib/pbkdf2.js, tests/unit/pbkdf2.js
> The default encoding for all crypto methods is utf8.
refer: [Breaking changes between v5 and v6](https://github.com/nodejs/node/wiki/Breaking-changes-between-v5-and-v6)
=> create password buffer with encoding binary

CHANGELOG.md, lib/asn1.js, lib/util.js, lib/x509.js, tests/unit/asn1.js, tests/unit/util.js, tests/unit/x509.js
- Fixes possible issues with certificate parsing.
- Eliminates many parsing failures. Often due to parsing BIT STREAMs as possible ASN.1 data.
- Improve many checks to protect against getting out of sync with byte stream.
- Add support for "raw" data to ensure BIT STREAM data stays constant while capturing or encoding when it may have mistakenly been interpreted as ASN.1 data.
=> Certificate parsing fixes.

lib/sha512.js
Without this change, PSS (using something other than sha1 / sha256 / sha512) could be incorrectly calculated, thereby throwing a `index out of range` error.
=> set correct digest size for hashes based on SHA-512

README.md
The Markdown (at least on GitHub) was not catching headings
just below the anchor tags.
=> Fix README header formatting

lib/prng.js
Addresses #520.
This isn't fully done yet, but it addresses:
1. Fixing the incorrect (reversed) condition for selecting pools to use entropy from when reseeding.
2. Includes the old key bytes when reseeding.
Some other concerns were raised in #520 that may need to be addressed -- or they may be ok, more research is needed.
=> Fix Fortuna implementation bugs.

lib/pkcs7.js, tests/unit/pkcs7.js
RFC 2315, section 9.1 explicitly says that the certificates attribute is
optional.
=> [pkcs7] Import signedData message with no certificates

lib/asn1.js
Discovered by the Closure Compiler:
$ closure-compiler --jscomp_warning=lintChecks dist/forge.all.js
[…]
dist/forge.all.js:3551: WARNING - unreachable code
for(var i = 0; i < obj1.length; ++i) {
^^^
=> asn1.equals: Compare all array elements, not just the first

lib/form.js
One regex in this project was vulnerable
to catastrophic backtracking.
I have replaced it with a safe regex that matches
a nearly-equivalent language.
I believe this language is still correct for the expected input.
This is a fix for #563.
=> Fix catastrophic backtracking

lib/util.js
When using a stock webpack config (which injects `process`), calling
`forge.utils.setImmedate` fails with `invalid calling object` on IE11
and Edge. 
A fix for this was implemented in #390 but the detection didn't
work properly. 
By checking also for `process.browser`, we can now properly
detect a webpack / browser environment and use the proper workaround for
the error (wrapping `setImmediate`)
=> Correctly detect webpack when trying to polyfill utils.setImmediate. Fixes regression in #385

README.md, lib/pkcs7.js, tests/unit/pkcs7.js
Adds `signDetached()` to the PKCS#7 implementation (see #279) as in my usecase it worked perfectly fine the way it was proposed 3 years ago by @fadlijuniarso. The same piece of code is being used in a number of repos on GitHub but what lead me here was the piece used in [pdfsign.js](https://github.com/Communication-Systems-Group/pdfsign.js/blob/master/src/lib/pkcs7-detached.js#L324) so thanks to @tbocek as well.
I've also added a test to cover `signDetached()`.
=> Add sign({detached: true}) to PKCS#7

README.md
Main README references testing README, which is a one-line file
pointing the reader back to main.
=> README: Remove circular documentation reference

lib/oids.js, lib/x509.js, tests/unit/x509.js
This extension is in theory deprecated, but remains widely used, and
supported by openssl and other tools.  It is a useful method to associate a
comment or memo with a certificate.
OID 2.16.840.1.113730.1.13 requires IA5STRING value for the comment.  We filter
for this requirement, and also to avoid creating pathologically long strings
by default.
=> x509: add support for Netscape comment extension

CHANGELOG.md, README.md, karma.conf.js, package.json, tests/unit/asn1.js, tests/unit/pkcs7.js, tests/unit/support.js
- PhantomJS is deprecated. Now using headless Chrome.
- See also: https://github.com/digitalbazaar/forge/pull/616
=> Switch tests from PhantomJS to headless Chrome.

lib/tls.js, lib/x509.js, tests/unit/x509.js
I would like to be able to check whether a particular certificate chain was valid at a specific date at which the certificate was used to sign a message. 
For this I added an additional parameter to `x509.verifyCertificateChain` with which the date at which the certificate's validity shall be checked can be specified. It defaults to the current date.
Passing `validityCheckDate` after the `verify` callback is a bit unfortunate, but adding it before the callback would be a breaking change and I'm not sure how strict you are with breaking changes at this point.
=> Custom validity period verification date

lib/cipherModes.js, tests/unit/aes.js
Addresses #666.
Previously, if streaming input to an AES-GCM cipher resulted in a partial block followed by a subsequent call with enough data to complete that previous block and enough start a new one, the authentication tag would be miscalculated. This was because of an errant comparison that did not account for this overflow into another block -- so a required code path would not be run. This PR fixes that bug and adds a test that guarantees data will be processed using `blockSize / 2 + 1` to ensure this condition occurs during the test -- and the proper authentication tag is produced.
@davidlehn if you find this PR acceptable, please pull it in and do a patch release.
=> Fix tag calculation when continuing an AES-GCM block.

lib/tls.js
Various files are encoded differently - I am not sure if this is intentional:
```
aes.js: UTF-8 Unicode text
aesCipherSuites.js: ASCII text
asn1.js: ASCII text
baseN.js: Algol 68 source text, ASCII text
cipher.js: ASCII text
cipherModes.js: Algol 68 source text, ASCII text
debug.js: ASCII text
des.js: ASCII text, with very long lines
ed25519.js: ASCII text
forge.js: ASCII text
form.js: Algol 68 source text, ASCII text
hmac.js: ASCII text
http.js: ASCII text
index.all.js: ASCII text
index.js: ASCII text
jsbn.js: ASCII text, with very long lines
kem.js: ASCII text
log.js: ASCII text
md.all.js: ASCII text
md.js: ASCII text
md5.js: ASCII text
mgf.js: ASCII text
mgf1.js: ASCII text
oids.js: ASCII text
pbe.js: ASCII text
pbkdf2.js: ASCII text
pem.js: ASCII text
pkcs1.js: ASCII text
pkcs12.js: …
```
=> Remove non breaking space from tls.js -- this causes issues on some browsers

CHANGELOG.md, README.md, lib/asn1.js, lib/ed25519.js, lib/pbkdf2.js, package.json, tests/benchmarks/so-44303784.js, tests/unit/ed25519.js
removes calls on node's new Buffer. This gets rid of deprecation notices.
> (node:45127) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
=> Deprecated node buffer

lib/oids.js
OID data taken from: http://oid-info.com/get/1.3.101.112 and 
It's not clear to me if the id should be `Ed25519`
https://tools.ietf.org/id/draft-ietf-curdle-pkix-01.html#rfc.section.3
or `EdDSA25519`
https://tools.ietf.org/id/draft-ietf-curdle-pkix-01.html#rfc.section.5
=> Add oid for EdDSA25519.

lib/ed25519.js
While this technically is not necessary, because node.js' Buffer
inherits from Uint8Array this contract is broken by jest.
See facebook/jest#4422.
Add a `message instanceof NativeBuffer` to the function to fix the issue,
it does no harm and *technically* would be the more correct check, because
for node.js passing a raw Uint8Array does not return a Buffer.
------
I can also adjust the function to wrap the `Uint8Array` in a `Buffer`, if `NativeBuffer === Buffer` to be super correct. Just let me know.
=> Check for NativeBuffer in ed25519#messageToNativeBuffer

CHANGELOG.md, lib/cipherModes.js, tests/unit/des.js
#721 highlights that a bad assumption was being made with the IV size in cipherModes.js. Additionally, the given IV was not being checked against the block size to help prevent user error.
@davidlehn, I'm out of time to work on this but we still need a test (we can use the information from #721 but adjust to ensure the given IV size is proper), could you add?
=> Ensure given IV matches block size.

CONTRIBUTING.md
It appears nodeguide.com domain has been taken over by domain squatters and the style.html page appears to push a questionable PDF download.
=> Remove link to nodeguide.com

lib/oids.js
The OIDs for surname, title and givenName were missing from the list in oids.js.
I need these OIDs to support certificates used by UZI pas cards. UZI pas is a means for Dutch healthcare professionals to identify themselves (see https://www.uziregister.nl/ and https://www.zorgcsp.nl/documents/RK1%20CPS%20UZI-register%20V10.2%20ENG.pdf). But these OIDs are very generic and probably usefull in many other cases.
This PR adds:
- 2.5.4.4 surname
- 2.5.4.12 title
- 2.5.4.42 givenName
=> Add OIDs for surname, title and givenName

SECURITY.md
Plain email will let markdown render as a mailto link.
=> Use plain email.

CHANGELOG.md, lib/oids.js
- OID 2.5.4.5 should be `serialNumber`.
@dlongley Was there a reason this id was using the wrong name?  Or was it just a typo?  What possible breakage could this cause?  Looking on the web, it seems the only places `serialName` comes up are places where people copied this code (oops!).
=> Fix OID `serialName` to `serialNumber`.

README.md, examples/create-cert.js, examples/create-csr.js, examples/create-pkcs12.js, examples/sign-p7.js
2048 bits has been the required minimum since 2014
=> 🔒 change CSR examples to use 2048 bit keys

lib/x509.js, tests/unit/x509.js
Fixes #875 
After the patch the example from the linked issue produces the following (correct) hashes:
```
subject 1cc2e7af4b76d25234e12415b453b0eb7ba6a1a5
issuer 797cf08c18f544b716136397e74594ead5be9398
```
=> FIX [x509] Certificate issuer and subject hash correctly computed

lib/x509.js
The 'Expected' Issuer should be the certificate that we are invoking `verify()` on. The 'Actual' issuer should be the issuer that is set on the child certificate. Currently, the error message that describes verification failures has these two fields reversed.
=> 'Expected' and 'Actual' issuers were backwards in verification failure message

CHANGELOG.md, lib/oids.js, lib/x509.js, tests/unit/x509.js
Update to:
- https://github.com/digitalbazaar/forge/pull/825
- https://github.com/digitalbazaar/forge/issues/826
Cleans up repeated code.
=> Added alternate OID 1.3.14.3.2.29 for sha1 with RSA

CHANGELOG.md, lib/rsa.js, tests/unit/rsa.js
- Includes change from https://github.com/digitalbazaar/forge/pull/965.
- Fixes test.
- Handles md2/md5 cases (untested, making a test is difficult).
- Thanks to @dhensby!
=> Allow DigestInfo.DigestAlgorith.parameters to be optional.
